'use client';

import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { DashboardLayout } from '../../../components/DashboardLayout';
import { AudioRecorder } from '../../../components/AudioRecorder';
import { TTSButton } from '../../../components/TTSButton';
import api from '../../../services/api';
import { Mic, CheckCircle2, RefreshCw } from 'lucide-react';

export default function SpeakingPractice() {
  const [topic, setTopic] = useState('Describe an important decision you made in your life. Explain why you made it and how it affected you.');
  const [isProcessing, setIsProcessing] = useState(false);
  const [evaluation, setEvaluation] = useState<any>(null);

  const handleAudioFinished = async (blob: Blob) => {
    setIsProcessing(true);
    setEvaluation(null);
    try {
      const formData = new FormData();
      formData.append('file', blob, 'recording.webm');
      formData.append('transcript', ''); // transcript will be generated by whisper

      const data = await api.post('/speaking/evaluate', formData);
      setEvaluation(data);
    } catch (err) {
      console.error('Error evaluating speech audio:', err);
      alert('Could not analyze speech. Please speak clearly and ensure microphone access is enabled.');
    } finally {
      setIsProcessing(false);
    }
  };

  const handleNewTopic = () => {
    const topics = [
      "Talk about a teacher who influenced you significantly. What subject did they teach and why was their approach special?",
      "Describe your dream job. What skills does it require and why do you think you would excel at it?",
      "Explain the impact of Artificial Intelligence on modern employment. Do you view it as a benefit or a risk?",
      "Describe a travel experience that changed your perspective. Where did you go and what did you learn?",
      "What is your favorite book or film? Explain the plot briefly and describe why it resonates with you."
    ];
    const nextIdx = Math.floor(Math.random() * topics.length);
    setTopic(topics[nextIdx]);
    setEvaluation(null);
  };

  return (
    <DashboardLayout>
      <div className="max-w-4xl mx-auto space-y-7 font-sans">
        
        {/* Title */}
        <div className="pb-1 border-b border-slate-200/80">
          <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-slate-900 flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center">
              <Mic className="w-5 h-5" />
            </div>
            <span>Speech Evaluator</span>
          </h1>
          <p className="text-slate-500 text-sm mt-1">
            Practice spontaneous English speaking. Record your voice, and get an instant AI evaluation of grammar, fluency, vocabulary, and pacing.
          </p>
        </div>

        {/* Practice Prompt Section */}
        <div className="p-6 rounded-2xl bg-white border border-slate-200 shadow-sm space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-xs text-blue-600 font-bold uppercase tracking-wider">Practice Prompt</span>
            <button 
              onClick={handleNewTopic}
              className="text-xs text-slate-500 hover:text-blue-600 font-medium flex items-center gap-1 transition-colors cursor-pointer"
            >
              <RefreshCw className="w-3.5 h-3.5" />
              <span>Change Topic</span>
            </button>
          </div>
          <p className="text-base font-semibold leading-relaxed text-slate-800">
            {topic}
          </p>
        </div>

        {/* Voice Input Recorder */}
        <div className="space-y-3">
          <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider text-center">Press the microphone to record your answer</h3>
          <AudioRecorder onStop={handleAudioFinished} isProcessing={isProcessing} />
        </div>

        {/* Evaluation Summary Results */}
        {evaluation && (
          <motion.div
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-6 mt-8"
          >
            {/* Score Grid */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3.5">
              {[
                { label: 'Fluency', val: evaluation.fluency_score, color: 'from-blue-600 to-cyan-600' },
                { label: 'Grammar', val: evaluation.grammar_score, color: 'from-purple-600 to-indigo-600' },
                { label: 'Vocabulary', val: evaluation.vocabulary_score, color: 'from-indigo-600 to-blue-600' },
                { label: 'Naturalness', val: evaluation.naturalness, color: 'from-rose-600 to-pink-600' }
              ].map((s) => (
                <div key={s.label} className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm text-center">
                  <span className="text-xs text-slate-500 font-semibold uppercase tracking-wider">{s.label}</span>
                  <div className={`text-3xl font-extrabold mt-1.5 bg-gradient-to-r ${s.color} bg-clip-text text-transparent`}>{s.val}/100</div>
                </div>
              ))}
            </div>

            {/* Performance analysis details */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              {/* Transcription and pace */}
              <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-3.5">
                <h3 className="font-bold text-sm text-slate-900 border-b border-slate-100 pb-2">Your Transcript</h3>
                <p className="text-sm italic leading-relaxed text-slate-700">
                  &ldquo;{evaluation.transcript}&rdquo;
                </p>
                <div className="pt-2 flex items-center justify-between text-xs text-slate-500 font-medium">
                  <span>Speaking Speed: <strong className="text-slate-800">{evaluation.speaking_speed} WPM</strong> (Target: 130-150)</span>
                  <span>Fillers: <strong className="text-slate-800">{evaluation.pause_analysis?.filler_count || 0}</strong></span>
                </div>
                {evaluation.pause_analysis?.description && (
                  <p className="text-xs text-slate-600 bg-slate-50 p-3 rounded-xl border border-slate-100">
                    <strong>Pacing advice:</strong> {evaluation.pause_analysis.description}
                  </p>
                )}
              </div>

              {/* Grammar Corrections */}
              <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-3.5">
                <h3 className="font-bold text-sm text-slate-900 border-b border-slate-100 pb-2 flex items-center gap-1.5">
                  <CheckCircle2 className="w-4 h-4 text-blue-600" />
                  <span>Grammar Corrections</span>
                </h3>
                
                {evaluation.suggested_corrections?.length === 0 ? (
                  <div className="flex items-center gap-2 text-blue-700 bg-blue-50/60 p-4 rounded-xl text-xs font-semibold">
                    <CheckCircle2 className="w-4 h-4" />
                    <span>Excellent grammar! No mistakes found.</span>
                  </div>
                ) : (
                  <div className="space-y-3 max-h-60 overflow-y-auto pr-1">
                    {evaluation.suggested_corrections?.map((err: any, idx: number) => (
                      <div key={idx} className="p-3 bg-slate-50 rounded-xl border border-slate-200/80 text-xs space-y-1">
                        <div className="flex items-baseline gap-1">
                          <span className="text-rose-600 font-semibold uppercase tracking-wider text-[10px]">Mistake:</span>
                          <span className="text-slate-500 italic line-through">&ldquo;{err.original}&rdquo;</span>
                        </div>
                        <div className="flex items-baseline gap-1">
                          <span className="text-indigo-700 font-semibold uppercase tracking-wider text-[10px]">Correction:</span>
                          <span className="text-slate-900 font-semibold">&ldquo;{err.corrected}&rdquo;</span>
                        </div>
                        <p className="text-slate-600 mt-1 font-normal leading-normal">{err.explanation}</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>

            {/* Improved version to read aloud */}
            <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-3">
              <div className="flex items-center justify-between">
                <h3 className="font-bold text-sm text-slate-900">Recommended Native Phrasing</h3>
                <TTSButton text={evaluation.improved_version} />
              </div>
              <p className="text-sm leading-relaxed text-slate-800 bg-blue-50/40 p-4 rounded-xl border border-blue-100/60">
                {evaluation.improved_version}
              </p>
              <div className="text-[11px] text-slate-400">
                Tip: Click the speaker button above to listen, then try reading it aloud to practice natural speech rhythm.
              </div>
            </div>

          </motion.div>
        )}

      </div>
    </DashboardLayout>
  );
}
